name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        # Is line mein hum 'yes' auto-reply kar rahe hain
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/user/hostdir \
          kivy/buildozer:latest /bin/bash -c "yes | buildozer android debug"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Ali-Sher-Printer-APK
          path: bin/*.apk
