name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        # Hum direct docker image istemal karenge jo Google Colab ki tarah kaam karti hai
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/user/hostdir \
          kivy/buildozer:latest --version && \
          docker run --rm -v ${{ github.workspace }}:/home/user/hostdir \
          kivy/buildozer:latest android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Ali-Sher-Printer-APK
          path: bin/*.apk
